# DJL ????????????
ai.djl.repository.maven.url=https://maven.aliyun.com/repository/public
# ?? DJL ?????????????????
ai.djl.huggingface.tokenizers.disable_platform_detection=false
# ???? Windows x64 ??????????
ai.djl.platform=windows-x86_64